export type Category = 'all' | 'product' | 'system' | 'experiment';
export interface ProjectLinks { live?: string; source?: string }
export interface Project {
 id: string; number: string; category: Exclude<Category,'all'>; name: string; year: string; headline: string;
 summary: string; role: string; tags: string[]; problem: string; decision: string; architecture: string[];
 result: string; next: string; context: string; demoHint: string;
 status: 'live' | 'building'; links: ProjectLinks; shot?: string;
}
export const social = {
 github: 'https://github.com/kevingtonee',
 linkedin: 'https://www.linkedin.com/in/japhet-nyangaresi-2185762aa/',
};
export const copy = {
  name:'Japhet Nyangaresi', roman:'JAPHET NYANGARESI', role:'Full-Stack Developer & AI Engineer', resumeLabel:'Resume / Portfolio',
  location:'Kenya · Remote-friendly', available:'Open for full-time, contract & freelance work',
  statusNote:'Real client work and products — every case links to the live build',
  nav:['Work','Experience','Contact'], eyebrow:'FULL-STACK ENGINEERING. APPLIED AI. REAL PAYMENTS.',
  statement:['Software for real business,','shipped end to end'],
  intro:'I design and build websites, business systems, e-commerce platforms and AI-powered applications — from database schema and API design to the interface people actually use.',
  viewWork:'View selected work', download:'Download resume', downloaded:'Your text resume is ready to download', downloadFailed:'Download failed. Please use Print resume below.',
  selected:'Selected work', selectedSub:'E-commerce, marketplaces, social & student tools',
  projectHint:'Working interaction slices inside · Live links in every case', all:'All work', product:'Products', system:'Platforms', experiment:'In the lab',
  resultCount:'projects', caseStudy:'View case study', close:'Close case study', challenge:'The challenge', approach:'The decisions',
  architecture:'How it is built', outcome:'What shipped', next:'What comes next', responsibility:'My contribution',
  demoLabel:'INTERACTION SLICE / LOCAL SAMPLE DATA', linksLabel:'Project links', liveLabel:'Live project', sourceLabel:'Source code', buildingLabel:'In development', shotCaption:'The live product, as shipped',
  aboutLabel:'A little about me', aboutTitle:['Business problems,','engineered answers'],
  aboutBody:'I ship complete products end to end — from database schema and API design to the interface people actually use. My work spans modern web apps (React, Next.js, Node.js, PostgreSQL) and applied AI: integrating LLM APIs, building agent and tool-use workflows, and using Python for classic machine learning. I care about security, performance, and code the next person can read.',
  principles:[['01','Business first','I don’t just write code — I build software that solves a business problem, from M-Pesa payments to marketplace escrow flows.'],['02','Ship end to end','Database, API, auth, payments, interface — I own the whole path and deploy it for real users.'],['03','Readable beats clever','Security, performance and tests matter; so does code the next engineer can pick up without me.']],
  experience:'Experience', experienceNote:'Client work, independent products and study',
  history:[
   {date:'2025 — Present',company:'Independent & client work',role:'Full-stack & AI Engineer',body:'Designing and shipping production software for real businesses — most recently ILANA, a jewellery e-commerce platform with real Safaricom M-Pesa Daraja STK Push payments, an admin dashboard and WhatsApp enquiries, deployed on Vercel with a Neon Postgres database.'},
   {date:'2024 — 2025',company:'Independent products',role:'Product Engineer',body:'Built and shipped ReMarket — a second-hand marketplace with discovery, listings, messaging and offers — and VibeMeet, a social platform with realtime messaging, both on Next.js / React with Supabase backends.'},
   {date:'2023 — Present',company:'Software engineering degree',role:'Student & builder',body:'Completing a software engineering degree while shipping real projects alongside — applying coursework in data structures, security and machine learning directly to client and product work.'}
  ],
  toolkit:'What I work with', toolNote:'The right tools, from first sketch to shipped product',
  skillGroups:[['Frontend','React · Next.js · TypeScript · Tailwind CSS'],['Backend & data','Node.js · REST APIs · PostgreSQL · Prisma · Supabase · Firebase'],['Payments','M-Pesa Daraja · STK Push · NextAuth v5 · Webhooks'],['AI engineering','OpenAI · Claude · Gemini · Agents & tool-use · Prompt engineering'],['Python & ML','Python · PyTorch · scikit-learn · Hugging Face'],['Practices','Git & GitHub · Vitest · CI/CD · OWASP Top 10 · Linux']],
  education:'Education & ongoing learning', educationText:'BSc Software Engineering — in progress · Kenya', educationExtra:'Deepening distributed systems, applied AI and application security.',
  contactTitle:['Have a project in mind?','Let’s build it together'],
  contactBody:'Tell me what you’re building, what problem you’re trying to solve, or what you need automated. I’m open to full-time roles, contract projects and freelance work.',
  copyEmail:'Copy email address', copied:'Email address copied', copyFailed:'Clipboard unavailable — please copy the address below manually',
  contactNote:'I usually reply within 24 hours.',
  formTitle:'Send a message', formName:'Name', formNamePlaceholder:'Your name', formNameError:'Please enter your name.',
  formEmail:'Email', formEmailPlaceholder:'you@example.com', formEmailError:'Please enter a valid email address.',
  formMessage:'Message', formMessagePlaceholder:'Tell me about the project or role...', formMessageError:'Tell me a little more about the project (at least 10 characters).',
  formSend:'Send message', formSending:'Sending...', formFix:'Please fix the highlighted fields and try again.',
  formSuccess:"Thanks — your message is on its way. I'll reply soon.", formFailed:'Something went wrong. Please email me directly.',
  formNetwork:'Network error. Please email me directly at ',
  print:'Print resume / Save PDF', footer:'Designed with judgment. Built with code.',
  sculpture:'Interactive wire sculpture', specimen:'FORM STUDY 001', sculptureHint:'Click sculpture to change form · Focus and use ← → to rotate · Play the signature below',
  pause:'Pause motion', play:'Resume motion', reset:'Reset form', reduced:'Reduced motion enabled', paused:'Paused', running:'In motion',
  skip:'Skip to work', language:'Switch language', concept:'Case study', printable:'Resume summary',
  socialsLabel:'Elsewhere',
  email:'japhetkevingtone@gmail.com',
};;
export const projects: Project[] = [
  {id:'ilana',number:'01',category:'product',name:'ILANA',year:'2026',headline:'Real M-Pesa payments for a real jewellery business',summary:'A production e-commerce platform for Ilana, a Kenyan jewellery retailer — live Safaricom M-Pesa Daraja STK Push payments, an admin dashboard and WhatsApp enquiries, deployed on Vercel with a Neon Postgres database.',context:'Client project · Shipped & live · Design + full-stack build',role:'Everything: schema, payments, admin, deployment',tags:['NEXT.JS 16','TYPESCRIPT','M-PESA DARAJA','POSTGRESQL','PRISMA'],problem:'A jewellery retailer was losing ready-to-buy customers to manual WhatsApp orders and “send money to this number” payments. They needed a real store: browse, pay by M-Pesa, and manage orders without calling a developer.',decision:'Sandbox-first M-Pesa Daraja integration with STK Push, a server-side order state machine and idempotent callbacks. Frankfurt-based serverless functions keep database round-trips close to the Neon Postgres region; NextAuth v5 separates the admin dashboard from the storefront.',architecture:['Next.js 16 storefront + admin','M-Pesa Daraja STK Push + callbacks','Prisma + Neon Postgres','Vercel Blob media + NextAuth v5'],result:'Live and taking real orders. Try the interaction slice below: add pieces to the cart and run a sandbox STK Push payment end to end — the full flow the production store uses.',next:'Loyalty and repeat-customer flows, richer admin analytics, and expanding the catalogue beyond jewellery lines.',demoHint:'Add pieces to the cart, then pay with M-Pesa — watch the STK Push flow.',status:'live',links:{live:'https://e-commerce-one-theta-84.vercel.app/',source:'https://github.com/kevingtonee/ilana-ecommerce'},shot:'/img/ilana.webp'},
  {id:'remarket',number:'02',category:'product',name:'ReMarket',year:'2025',headline:'Buy smart. Sell what you no longer need.',summary:'A production-ready second-hand marketplace: discovery, listings, realtime messaging and offers — with payments, delivery, escrow and verification designed as clean future additions.',context:'Independent product · V1 live · Design + full-stack build',role:'Product design, data model, realtime messaging',tags:['NEXT.JS 15','SUPABASE','REALTIME','SHADCN/UI','ZOD'],problem:'Campus and neighbourhood selling runs on chaotic chat groups: no search, no price history, no way to know what actually sold. Buyers scroll forever; sellers repost the same listing every week.',decision:'Model the listing lifecycle explicitly — draft, live, offer, sold — instead of bolting states onto a posts table. Supabase Realtime powers offers and messaging; Zod-validated forms keep listings structured enough to actually search and filter.',architecture:['Next.js 15 + shadcn/ui storefront','Supabase Postgres + Realtime','Offer & message state machine','Zod + React Hook Form validation'],result:'V1 is live with discovery, listings, messaging and offers. The slice below is the offer flow: search the listings, open one, and negotiate with a very patient seller.',next:'Payments, delivery coordination, escrow and identity verification — designed for, not shipped yet.',demoHint:'Search the listings, open one, and make an offer — the seller answers.',status:'live',links:{live:'https://remarket-ecru.vercel.app/',source:'https://github.com/kevingtonee/remarket'},shot:'/img/remarket.webp'},
  {id:'vibemeet',number:'03',category:'system',name:'VibeMeet',year:'2025',headline:'Realtime messaging people can actually feel',summary:'A social connect platform with realtime messaging, profiles and content sharing — React on the front, Supabase handling auth, storage and realtime subscriptions.',context:'Independent product · Live · Frontend + backend',role:'Realtime architecture, profiles, messaging UX',tags:['REACT','SUPABASE','REALTIME','TAILWIND CSS'],problem:'Most student social apps feel dead because nothing moves until you refresh. Connection — the whole point — needs presence, instant delivery, and conversations that update as they happen.',decision:'One Supabase Realtime channel per conversation, optimistic message rendering with reconciliation, and presence heartbeats so “online” actually means online. Auth and storage rules are enforced in Postgres row-level security, not just in the UI.',architecture:['React SPA + Tailwind frontend','Supabase auth + RLS policies','Realtime channel per conversation','Optimistic sends + reconciliation'],result:'Live with profiles, sharing and realtime chat. The slice below is the messaging core: switch channels, send a message, and watch the reply land without a refresh.',next:'Group calls, notification digests and moderation tooling as the community grows.',demoHint:'Switch channels and send a message — replies arrive in realtime.',status:'live',links:{live:'https://mmu-vibe-meet.netlify.app/',source:'https://github.com/kevingtonee/vibeMeet-frontend'}},
  {id:'studenthub',number:'04',category:'experiment',name:'Student Hub',year:'2026',headline:'A calmer way to run student life',summary:'A student hub for course scheduling, grade tracking and study groups — currently being built with Next.js and Supabase, and dogfooded on my own degree.',context:'In development · Own product · Design + full-stack',role:'Everything so far: schema, planner, grade model',tags:['NEXT.JS','SUPABASE','TYPESCRIPT'],problem:'Timetables live in PDFs, grades in WhatsApp screenshots, study groups across three different apps. Students plan the week from memory and find out about clashes the hard way.',decision:'Model the week as first-class data — recurring class blocks, not hand-typed calendar events — so clash detection and “what do I have today” are queries, not features. Grade tracking computes standing continuously, not at exam-panic time.',architecture:['Next.js + TypeScript app','Supabase Postgres + auth','Recurring schedule model','Continuous grade computation'],result:'The planner and grade tracker below are the working core, running on sample data from a real week. Scheduling and study groups ship next.',next:'Study-group matching, deadline reminders and a proper mobile shell. Links land here as it ships.',demoHint:'Switch days to browse the timetable; grade bars update live.',status:'building',links:{}}
 ];
